[network.internet]
title = "Internet"
description = "The public internet"
protocols = ["protocol.ipv4", "protocol.ipv6"]

[network.cable]
title = "Comcast Network"
description = "The "
protocols = ["protocol.ipv4", "protocol.ipv6"]
interfaces = [{network="network.internet"}]

[network.center]
title = "Center Street"
description = """
Main office network.
"""
protocols = ["protocol.ipv4", "protocol.wifi"]
ipv4_ranges = ["20.70.122.13/29"]

[network.prod]
title = "Production"
description = """
Production Network
"""
protocols = ["protocol.ipv4", "protocol.wifi"]
ipv4_ranges = ["192.168.1.0/24"]
controls.ingress_default = "deny"
controls.egress_default = "allow"
controls.ingress = [
		 {flows=["flow.https"], destinations=["server.prod"], controller="server.prod-fw"},
 		 {flows=["flow.ssh-keypair"], destinations=["server.prod"], controller="server.prod-fw"}]

[server.cable-router]
title = "Comcast Router"
interfaces = [{network="network.center", address="20.70.122.13", downstream=true},
	      {network="network.cable", address="83.153.3.143"}]
owner = "cable"

[server.prod-fw]
title = "Production Firewall"
interfaces = [{network="network.center", address="20.70.122.14"},
	      {network="network.prod", address="192.168.1.1", downstream=true}]
os = "linux"
version = "ubuntu 20"

[server.prod]
title = "Production"
interfaces = [{network="network.prod"}]
os = "linux"
version = "ubuntu 20"
applications = ["application.mainapp",]
stores = ["store.main-mysql", "store.prod-fs"]

[store.main-mysql]
title = "Production MySQL"
data = ["data.health-info", "data.login-credentials", "data.health-metadata"]
backing = "store.prod-fs"

[store.prod-fs]
title = "Production Filesystem"
data = ["data.health-info"]

[flow.mainapp-backend]
title = "PHP WebApp Backend"
sources = ["application.mainapp"]
data = ["data.health-info", "data.login-credentials"]
destinations = ["store.prod-fs", "store.main-mysql"]

[data.login-credentials]
title = "Login Credentials"
description = "Passwords used by clients and employees to login to main app"
classification = "classification.confidential"

[deployment.mainapp]
description = "Multi-tenant instance"
applications = ["application.mainapp"]
targets = ["server.prod"]

[application.mainapp]
title = "PHP WebApp"
description = """
A multi-tenant Application instance
"""

[actor.client]
title = "Client"
description="A client"

[endpoint.client-computer]
title = "Client Computer"
description="A client's computer"
interfaces = [{network="network.internet"}]
agents = ["agent.client-ssh", "agent.client-browser"]

[agent.client-browser]
title = "Client Browser"
description = "Clients using a web browser on their computer."
process = "process.web-browser"
actor = "actor.client"

[flow.mainapp-client]
sources = ["agent.client-browser"]
destinations = ["application.mainapp"]
data = ["data.login-credentials", "data.health-info"]
channel = "channel.https"

[data.health-info]
title = "Health Information"
classification = "classification.high-risk"
regulations = ["regulation.phi", "regulation.pii"]

[data.health-metadata]
title = "Health Metadata"
classification = "classification.sensitive"

[channel.ipv4]
protocols = ["protocol.ipv4"]

[channel.ipv6]
protocols = ["protocol.ipv4"]

[channel.ip]
protocols = ["protocol.ipv4", "protocol.ipv6"]

[channel.tcp]
protocols = ["protocol.ipv4", "protocol.ipv6"]

[channel.ssh-keypair]
over = ["channel.ipv4"]
ports = [22]
protocols = ["protocol.ssh"]
authentication = "authentication.ssh-keypair"
encryption = "encryption.ssh-ciphers"

[channel.wpa2-wifi]
protocols = ["protocol.wifi"]
authentication = "authentication.wpa2"
encryption = "encryption.wifi"

[channel.https]
ports = [443]
protocols = ["protocol.https"]
encryption = "encryption.tls"

[risk.ipv6-unmanaged]
title = "IPv6 Protocol enabled, but not managed"

[risk.credential-stuffing]
title = "Credential Stuffing"
description = """
Attackers can try common passwords, or passwords associated with user from other leaks to attempt to login.  This can be mitigated thru several means:

Mitigations:

* Require Multi-Factor Auth
* Require authenticated network access via VPN
* Limit access to login to client IPs (by ASN or CIDR)
* Use SSL Client certificates for client (a form of MFA)
"""

[risk.pre-auth-attack-surface]
title = "Pre-Auth Vulnerabilities"
description = """
Attackers can access or manipulate data without authenticating due to vulnerabilities in the application authentication logic, or system configuration.

* Use SSL Client certificates for client (a form of MFA)
* Require authenticated network access via VPN
* Limit access to login to client or employee IPs (by ASN or CIDR)
"""

[risk.unmanaged-device]
title = "Unmanaged Device"
description = """
A device or computer that a user is using to access the system is unamanaged.  This leads to inconsistent, or unknown security posture, reduced observabiilty, and potential for exploitation.
"""

[risk.vulnerable-software]
title = "Unmanaged Device"
description = """
A device or computer that a user is using to access the system is unamanaged.  This leads to inconsistent, or unknown security posture, reduced observabiilty, and potential for exploitation.
"""

[risk.unauthenticated-service]
title = "Unauthenticated Service"
description = """
A service is listening on a network which does not require credentials, and presumes that network access is a sufficient control.
"""

[risk.no-remote-backup]
title = "No remote Backup"
description = """
The store has no offsite backup policy, or validated offsite backup.
"""

[risk.no-backup]
title = "No Backup"
description = """
The store has no backup policy, or validated backup.
"""

[risk.third-party-control]
title = "Third Party Control"
description = """
The resource is owned and operated by a third-party, which managed updates
"""

[risk.inconsistent-updates]
title = "Inconsistent Updates"
description = """
The resource does not receive consistent updates, which can result in unpatched vulnerabilities.

Mitigation:
* establish a automated, or scheduled update process
"""

[risk.unaudited-controls]
title = "Unaudited Controls"
description = """
A security control should have regular audits to ensure that it is effective and behaving as expected.
"""

[regulation.hipaa-phi]
title = "HIPAA Protected Health Information"
description = """
Protected health information (PHI) under U.S. law is any information about health status, provision of health care, or payment for health care that is created or collected by a Covered Entity (or a Business Associate of a Covered Entity), and can be linked to a specific individual. This is interpreted rather broadly and includes any part of a patient's medical record or payment history.

Under the U.S. Health Insurance Portability and Accountability Act (HIPAA), PHI that is linked based on the following list of 18 identifiers must be treated with special care:

- Names
- All geographical identifiers smaller than a state, except for the initial three digits of a zip code if, according to the current publicly available data from the U.S. Bureau of the Census: the geographic unit formed by combining all zip codes with the same three initial digits contains more than 20,000 people; the initial three digits of a zip code for all such geographic units containing 20,000 or fewer people is changed to 000
- Dates (other than year) directly related to an individual
- Phone Numbers
- Fax numbers
- Email
- Social Security numbers
- Medical record numbers
- Health insurance beneficiary numbers
- Account numbers
- Certificate/license numbers
- Vehicle identifiers and serial numbers, including license plate numbers;
- Device identifiers and serial numbers;
- Web Uniform Resource Locators (URLs)
- Internet Protocol (IP) address numbers
- Biometric identifiers, including finger, retinal and voice prints
- Full face photographic images and any comparable images
- Any other unique identifying number, characteristic, or code except the unique code assigned by the investigator to code the data

"""

[regulation.hipaa-security-rule]
title = "HIPAA Security Rule"
description = """

HIPAA Security Rule Details: <https://www.ecfr.gov/current/title-45/part-164/subpart-C>

Written forms of the following policies are required

Security Rule Requirements:

* Security Management Process
  * Risk Analysis (Required)
  * Risk Management (Required)
  * Sanction Policy (Required)
  * Information System Activity Review (Required)
* Assigned Security Responsibility 
* Workforce Security
  * Authorization/Supervision Procedure
  * Workforce Clearance Procedure
  * Termination Procedure
* Information Access
  * Isolation of Funcion (Required)
  * Access Authorization/Review Process
* Security Awareness Training
  * Periodic Reminders/Updates for workforce
  * malware protection (AV/EDR)
  * log-in monitoring (workstation, applications)
  * credential management
* Incident Response Policy  
* Contigency Plan (Required)
  * Data Backup Plan (Required)
  * Disaster Recovery Plan (Required)
  * Emergency Mode Plan (Required)

* Physical Safeguards
  * Facilities Access Control Policy
* Workstation Security
  * Password Required
  * Media Re-Use and Disposal Policy
  * Backup Policy

* Access Control
  * Unique User Identifiers
  * Emergency Access
  * Automatic Logoff
  * Encryption
    * Transmission
    * At Rest/Storage
* Audit Controls
  * Offhost audit logs
  

These policies must be written, and stored in compliance with:
<https://www.ecfr.gov/current/title-45/section-164.316>

A convenient Security Standards Matrix is here:
<https://www.ecfr.gov/current/title-45/part-164/appendix-Appendix A to Subpart C of Part 164>

"""

